name: Docs Deploy
on:
  push:
    branches: ["development"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: zcloudws/zcloud-cli
      env:
        ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --rm -t wallety/wallety-portal:latest .

      - name: Deploy with Quave Cloud CLI
        if: success() # Only runs if the previous step (docker build) succeeds
        env:
          ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}
        run: zcloud deploy --env "wallety-walletyportal-3-staging"
