name: Docs Deploy

on:
  push:
    branches: ["development"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove conflicting Docker packages
        run: |
          sudo apt-get remove -y containerd docker docker-engine docker.io
          sudo apt-get autoremove -y

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image
        run: |
          docker build --rm -t wallety/wallety-portal:latest \
            --build-arg NODE_ENV=${{ secrets.DEV_NODE_ENV }} \
            --build-arg NG_APP_NAME=${{ secrets.DEV_NG_APP_NAME }} \
            --build-arg NG_APP=${{ secrets.DEV_NG_APP }} \
            --build-arg NG_APP_USER_STORAGE_NAME=${{ secrets.DEV_NG_APP_USER_STORAGE_NAME }} \
            --build-arg NG_APP_API_URL=${{ secrets.DEV_NG_APP_API_URL }} .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    container:
      image: zcloudws/zcloud-cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with Quave Cloud CLI
        env:
          ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}
        run: zcloud deploy --env "wallety-walletyportal-7-development" --dir "."
