name: Docs Deploy

on:
  push:
    branches: ["development"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - name: Start Docker-in-Docker
        run: |
          dockerd-entrypoint.sh &
          sleep 10

      - name: Install Docker CLI
        run: apk add --no-cache docker-cli

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --rm -t wallety/wallety-portal:latest .

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    container:
      image: zcloudws/zcloud-cli
      env:
        ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify source directory
        run: ls -la ./ && pwd

      - name: Deploy with Quave Cloud CLI
        env:
          ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}
        run: zcloud deploy --env "wallety-walletyportal-7-development" --dir "."
